#!/bin/sh

IS_RUNNING="$(ps -ef | grep caffeinate | grep -v grep)"
sudo -s <<EOF
function cleanup() {
    echo "Resetting disablesleep"
    pmset -a disablesleep 0
    exit
}

echo "Setting disablesleep"
pmset -a disablesleep 1
pmset -a sleep 0

trap 'cleanup' 2

if [ -z "$IS_RUNNING" ]; then
    echo "Caffeinating..."
    nohup caffeinate -di > /dev/null &
fi
EOF
